version: '3'

services:
  n-pos:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/n-pos
    working_dir: /n-pos
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    entrypoint: npm
    env_file:
      - .env
    depends_on:
      - n-pos-db
  n-pos-db:
    image: postgres:14.5
    container_name: n-pos-db
    volumes:
      - n-pos-db:/var/lib/postgresql/data
    ports:
      - 4005:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  n-pos-db:
    external: true
